import * as THREE from 'three';
import './style.css';
import {TecnomageController,type TecnomageState} from './tecnomage';

const scene=new THREE.Scene();scene.background=new THREE.Color(0x07120f);scene.fog=new THREE.FogExp2(0x10251d,.026);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,160),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;document.querySelector('#app')!.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xa6ddff,0x112f1a,2));const sun=new THREE.DirectionalLight(0xffe7bd,4);sun.position.set(-12,18,8);sun.castShadow=true;scene.add(sun);
const ground=new THREE.Mesh(new THREE.CircleGeometry(24,64),new THREE.MeshStandardMaterial({color:0x193d27,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const trunkMat=new THREE.MeshStandardMaterial({color:0x4b3323}),leafMats=[0x28643a,0x347646,0x205a35].map(color=>new THREE.MeshStandardMaterial({color,roughness:.9}));type Obstacle={p:THREE.Vector3,r:number};const obstacles:Obstacle[]=[];
function tree(x:number,z:number,s=1,variant=0){const g=new THREE.Group(),t=new THREE.Mesh(new THREE.CylinderGeometry(.22,.34,2.6,7),trunkMat);t.position.y=1.3;t.castShadow=true;g.add(t);for(let i=0;i<3;i++){const c=new THREE.Mesh(new THREE.ConeGeometry(1.25-i*.15,2.2,7+variant%3),leafMats[variant%3]);c.position.y=2.6+i*.75;c.rotation.y=variant*.37;c.castShadow=true;g.add(c)}g.position.set(x,0,z);g.scale.setScalar(s);scene.add(g);obstacles.push({p:new THREE.Vector3(x,0,z),r:.5*s})}for(let i=0;i<46;i++){const a=i*2.399,r=9+(i%10)*1.25;tree(Math.cos(a)*r,Math.sin(a)*r,.7+(i%6)*.09,i)}
const rockMat=new THREE.MeshStandardMaterial({color:0x53615a,roughness:1});for(let i=0;i<28;i++){const a=i*1.77,r=5+(i%9)*1.6,x=Math.cos(a)*r,z=Math.sin(a)*r;if(Math.hypot(x+5,z+6)<3)continue;const m=new THREE.Mesh(new THREE.DodecahedronGeometry(.18+(i%4)*.08),rockMat);m.position.set(x,.15,z);m.scale.y=.55;m.rotation.set(i*.2,i*.37,0);m.castShadow=true;scene.add(m)}
const grassMat=new THREE.MeshStandardMaterial({color:0x3f7c46,side:THREE.DoubleSide});for(let i=0;i<110;i++){const a=i*2.31,r=3+(i%19)*.95,x=Math.cos(a)*r,z=Math.sin(a)*r;if(Math.hypot(x,z)<2.2)continue;const g=new THREE.Mesh(new THREE.ConeGeometry(.10,.48,3),grassMat);g.position.set(x,.22,z);g.rotation.y=a;scene.add(g)}
const tecnomage=new TecnomageController();const player=tecnomage.root;scene.add(player);void tecnomage.load();
const energyMat=new THREE.MeshStandardMaterial({color:0x28e0c0,emissive:0x087b70,emissiveIntensity:3}),nexus=new THREE.Group(),ringMat=new THREE.MeshStandardMaterial({color:0x172e34,metalness:.8,roughness:.25,emissive:0x093b48,emissiveIntensity:1.5});for(let i=0;i<3;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(1.15+i*.25,.045,8,48),ringMat);ring.rotation.set(Math.PI/2,i*.7,i*.35);nexus.add(ring)}nexus.add(new THREE.Mesh(new THREE.IcosahedronGeometry(.35,2),energyMat));nexus.position.set(-5,2,-6);scene.add(nexus);
const keys=new Set<string>();let dodge=0,pulse=0;addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='KeyQ'){pulse=.32;tecnomage.pulse()}if(e.code==='Space'&&dodge<=0)dodge=.28});addEventListener('keyup',e=>keys.delete(e.code));let yaw=.65,pitch=.42,drag=false,px=0,py=0;renderer.domElement.addEventListener('pointerdown',e=>{drag=true;px=e.clientX;py=e.clientY});addEventListener('pointerup',()=>drag=false);addEventListener('pointermove',e=>{if(!drag)return;yaw-=(e.clientX-px)*.006;pitch=Math.max(.15,Math.min(1.05,pitch+(e.clientY-py)*.004));px=e.clientX;py=e.clientY});
const clock=new THREE.Clock(),up=new THREE.Vector3(0,1,0),ray=new THREE.Raycaster();function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.04),v=new THREE.Vector3((keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),0,(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0));dodge=Math.max(0,dodge-dt);pulse=Math.max(0,pulse-dt);let state:TecnomageState=pulse>0?'PULSE':dodge>0?'DODGE':'IDLE';if(v.lengthSq()){v.normalize().applyAxisAngle(up,yaw);const sprint=keys.has('ShiftLeft'),speed=dodge>0?13:sprint?7:4,next=player.position.clone().addScaledVector(v,speed*dt);if(!obstacles.some(o=>next.distanceTo(o.p)<o.r+.34))player.position.copy(next);player.rotation.y=Math.atan2(v.x,v.z);if(!pulse)state=dodge>0?'DODGE':sprint?'SPRINT':'RUN'}tecnomage.update(dt,state);const target=new THREE.Vector3(player.position.x,1.2,player.position.z),desired=new THREE.Vector3(player.position.x+Math.sin(yaw)*Math.cos(pitch)*8,player.position.y+Math.sin(pitch)*8+1,player.position.z+Math.cos(yaw)*Math.cos(pitch)*8),dir=desired.clone().sub(target),max=dir.length();ray.set(target,dir.normalize());const hits=ray.intersectObjects(scene.children,true).filter(h=>h.object!==ground&&!player.getObjectById(h.object.id)&&!nexus.getObjectById(h.object.id));const safe=hits.length&&hits[0].distance<max?Math.max(1.6,hits[0].distance-.35):max;camera.position.copy(target).addScaledVector(dir,safe);camera.lookAt(target);nexus.rotation.y+=dt*.35;nexus.children.forEach((c,i)=>c.rotation.z+=dt*(.12+i*.05));renderer.render(scene,camera)}loop();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
