import * as THREE from 'three';
import './style.css';

const scene=new THREE.Scene(); scene.background=new THREE.Color(0x07120f); scene.fog=new THREE.FogExp2(0x10251d,.028);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,160); camera.position.set(8,6,10);
const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setSize(innerWidth,innerHeight); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.15; document.querySelector('#app')!.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0x9fd8ff,0x16351e,2)); const sun=new THREE.DirectionalLight(0xffe7bd,4); sun.position.set(-12,18,8); sun.castShadow=true; scene.add(sun);
const ground=new THREE.Mesh(new THREE.CircleGeometry(24,64),new THREE.MeshStandardMaterial({color:0x193d27,roughness:1})); ground.rotation.x=-Math.PI/2; ground.receiveShadow=true; scene.add(ground);
const trunkMat=new THREE.MeshStandardMaterial({color:0x4b3323}); const leafMat=new THREE.MeshStandardMaterial({color:0x28643a,roughness:.9});
function tree(x:number,z:number,s=1){const g=new THREE.Group();const t=new THREE.Mesh(new THREE.CylinderGeometry(.22,.34,2.6,7),trunkMat);t.position.y=1.3;t.castShadow=true;g.add(t);for(let i=0;i<3;i++){const c=new THREE.Mesh(new THREE.ConeGeometry(1.25-i*.15,2.2,8),leafMat);c.position.y=2.6+i*.75;c.castShadow=true;g.add(c)}g.position.set(x,0,z);g.scale.setScalar(s);scene.add(g)}
for(let i=0;i<38;i++){const a=i*2.399,r=10+(i%8)*1.25;tree(Math.cos(a)*r,Math.sin(a)*r,.75+(i%5)*.1)}
const player=new THREE.Group(); const bodyMat=new THREE.MeshStandardMaterial({color:0x252b34,metalness:.25,roughness:.5}); const coreMat=new THREE.MeshStandardMaterial({color:0x28e0c0,emissive:0x087b70,emissiveIntensity:3}); const torso=new THREE.Mesh(new THREE.BoxGeometry(.75,1.15,.42),bodyMat);torso.position.y=1.35;player.add(torso);const head=new THREE.Mesh(new THREE.BoxGeometry(.48,.48,.48),bodyMat);head.position.y=2.15;player.add(head);const core=new THREE.Mesh(new THREE.OctahedronGeometry(.16),coreMat);core.position.set(0,1.42,.28);player.add(core);for(const x of [-.23,.23]){const leg=new THREE.Mesh(new THREE.BoxGeometry(.22,.8,.25),bodyMat);leg.position.set(x,.48,0);player.add(leg)}player.traverse(o=>{if(o instanceof THREE.Mesh)o.castShadow=true});scene.add(player);
const nexus=new THREE.Group();const ringMat=new THREE.MeshStandardMaterial({color:0x172e34,metalness:.8,roughness:.25,emissive:0x093b48,emissiveIntensity:1.5});for(let i=0;i<3;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(1.15+i*.25,.045,8,48),ringMat);ring.rotation.set(Math.PI/2,i*.7,i*.35);nexus.add(ring)}const orb=new THREE.Mesh(new THREE.IcosahedronGeometry(.35,2),coreMat);nexus.add(orb);nexus.position.set(-5,2,-6);scene.add(nexus);
const keys=new Set<string>();addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='KeyQ'){coreMat.emissiveIntensity=12;setTimeout(()=>coreMat.emissiveIntensity=3,180)}});addEventListener('keyup',e=>keys.delete(e.code));let yaw=.65,pitch=.42,drag=false,px=0,py=0;renderer.domElement.addEventListener('pointerdown',e=>{drag=true;px=e.clientX;py=e.clientY});addEventListener('pointerup',()=>drag=false);addEventListener('pointermove',e=>{if(!drag)return;yaw-=(e.clientX-px)*.006;pitch=Math.max(.15,Math.min(1.05,pitch+(e.clientY-py)*.004));px=e.clientX;py=e.clientY});
const clock=new THREE.Clock();function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.04),v=new THREE.Vector3((keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),0,(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0));if(v.lengthSq()){v.normalize();const speed=keys.has('ShiftLeft')?7:4;v.applyAxisAngle(new THREE.Vector3(0,1,0),yaw);player.position.addScaledVector(v,speed*dt);player.rotation.y=Math.atan2(v.x,v.z)}const d=8;camera.position.set(player.position.x+Math.sin(yaw)*Math.cos(pitch)*d,player.position.y+Math.sin(pitch)*d+1,player.position.z+Math.cos(yaw)*Math.cos(pitch)*d);camera.lookAt(player.position.x,1.2,player.position.z);nexus.rotation.y+=dt*.35;nexus.children.forEach((c,i)=>c.rotation.z+=dt*(.12+i*.05));renderer.render(scene,camera)}loop();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
